### ISSUE TITLE
failure to register FIDO2 device for new user as administrator

### ISSUE THREAD

**Issue by corbolais** [WordPress/two-factor#336] opened 2020-03-09 16:37 UTC
Just created a new user. Tried to add the Solo key as FIDO2 device to this user's device list. It does reload the user page but no device is registered nor any message logged.

**Proposition**: 
+ provide means to be able to register a new device to the newly created user's FIDO2 device list and display any failures in this process. 

OR: 
+ make it clear only logged in users can register a new device to their own FIDO2 device list. 

BONUS: explicitely mention administrators inability to add devices to user's FIDO2 device lists.

Local versions: WP 5.3.2, latest two-factor plugin version

**Comment by kasparsd** [comment] 2020-03-09 17:43
Thanks for reporting this @corbolais! Is this related to #88 -- are you trying to add a key to another user? Is that part of a WP multisite or regular install?

**Comment by corbolais** [comment] 2020-03-09 22:18
@kasparsd yes, 1st user tries to add a FIDO2 key to 2nd user.

It's a regular install.

**Comment by assarbad** [comment] 2020-03-22 17:23
@corbolais just curious, you seem to be mixing FIDO2 and FIDO Universal 2nd Factor (also oftentimes referred to as just U2F or FIDO U2F) here. Is this plugin even supposed to support FIDO2 (Webauthn)?

Admittedly this one is a bit on the FIDO alliance rather than the plugin authors. Just thinking that if your device supports FIDO2 it doesn't necessarily support FIDO U2F.

However, I think (at least firmware-wise) your Solokey may be related to the Nitrokey FIDO2, which _does_ support U2F as well.

**Comment by corbolais** [comment] 2020-03-22 20:11
@assarbad 

[Solokey](https://solokeys.com/) is a FIDO2 device.

https://github.com/WordPress/two-factor/ supports FIDO2

**Comment by kasparsd** [comment] 2020-04-30 11:08
Marking this a duplicate of #88.

**Closed by kasparsd** 2020-04-30 11:08 UTC
Labels: FIDO U2F

**Comment by assarbad** [comment] 2020-04-30 22:56
> https://github.com/WordPress/two-factor/ supports FIDO2
Fair enough, for some reason it doesn't work for me then.
