### ISSUE TITLE
Clicking on "Register New Key" in Safari 15 shows endless loading in WordPress 5.9.3

### ISSUE THREAD

**Issue by S0ulf3re** [WordPress/two-factor#440] opened 2022-04-25 00:02 UTC
When I try to add my Yubikey to my wordpress, it just stalls. Also, I tried setting up TOTP, and it doesn't seem to be asking for it on a new login

**Comment by TheCableGuy99** [comment] 2022-08-26 02:48
Trying to add my Yubikey on Edge and its just hanging also.

**Comment by kasparsd** [comment] 2022-08-26 07:06
Could you please confirm if this is a duplicate of #423 which is related to U2F API being removed from browsers earlier this year?

**Comment by S0ulf3re** [comment] 2022-08-26 08:40
Probably.

**Comment by TheCableGuy99** [comment] 2022-08-26 17:35
I couldn't tell you. All I know is it just spins when trying to add a key and doesn't work. Nothing in the logs, nothing trying to popup and other plugins work. I've installed the Yubikey plugin for now.

**Comment by kasparsd** [comment] 2022-09-08 14:29
Thanks for the update. I'll close this out until we have steps to replicate the issue. My best bet is #423 as mentioned earlier.

**Closed by kasparsd** 2022-09-08 14:29 UTC
Labels: Question, FIDO U2F
