### ISSUE TITLE
Fido2 registration of new key broken

### ISSUE THREAD

**Issue by thorko** [WordPress/two-factor#488] opened 2022-10-28 08:27 UTC
When trying to register a new key I'll get the following error 
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null')
```
Registering of new keys doesn't work

**Comment by iandunn** [comment] 2022-11-02 20:56
Are you using an extra plugin to support FIDO2? Right now `two-factor` only supports FIDO1.

You'll get that error message when trying to register a new FIDO1 key, because Chrome has deprecated it (see #423). It should still work in Firefox, though. This plugin is in the process of removing support for FIDO1 (#439), and adding support for FIDO2 (#427).

In the mean time, a plugin like https://github.com/sjinks/wp-two-factor-provider-webauthn will add FIDO2 support.

I'm gonna go ahead and close this since it seems like a duplicate of #423, but we can reopen if there's something distinct.

**Closed by iandunn** 2022-11-02 20:56 UTC
