### ISSUE TITLE
'Failed to create a login nonce' notification

### ISSUE THREAD

**Issue by mikolajek** [WordPress/two-factor#501] opened 2022-11-29 16:30 UTC
Hi there, today, out of the blue, my site with Two-Factor 0.7.3 installed started to display the "Failed to create a login nonce" notification. I'm running WP 6.1.1 and it seems to me the latest WP upgrade (6.1 => 6.1.1) might have caused this, as I made no changes to the config myself.

I disabled the plugin by renaming its folder, but in this case, I can't log in either. The login screen just keeps refreshing and gets back to the credentials screen. Is there a way to disable the plugin and get to the WP admin screen?

BTW - I have no cache plugin and clearing just the browser cache doesn't work...

**Comment by pkevan** [comment] 2023-01-27 10:42
Duplicate of: https://wordpress.org/support/topic/failed-to-create-a-login-nonce-message/

**Comment by mikolajek** [comment] 2023-01-27 10:46
> Duplicate of: https://wordpress.org/support/topic/failed-to-create-a-login-nonce-message/

Correct, but no response in either place... :P

**Comment by kasparsd** [comment] 2023-01-27 10:49
I haven't been able to replicate this with plugin version 0.7.3 and WP 6.1.1.

@mikolajek Which of the two-factor methods do you have enabled and which one is selected as the default?

**Comment by kasparsd** [comment] 2023-01-27 10:51
There are three code paths where this error message is returned:

https://github.com/WordPress/two-factor/blob/b67c7daca79b2cfed26147cd430f2497f9f55fcd/class-two-factor-core.php#L549-L552

https://github.com/WordPress/two-factor/blob/b67c7daca79b2cfed26147cd430f2497f9f55fcd/class-two-factor-core.php#L896-L904

https://github.com/WordPress/two-factor/blob/b67c7daca79b2cfed26147cd430f2497f9f55fcd/class-two-factor-core.php#L906-L917

**Comment by mikolajek** [comment] 2023-01-27 10:52
Thanks, @kasparsd! I use Yubikey as the default method and emailed OTP as the backup one.

**Comment by dd32** [comment] 2023-05-03 07:05
> I disabled the plugin by renaming its folder, but in this case, I can't log in either. The login screen just keeps refreshing and gets back to the credentials screen. Is there a way to disable the plugin and get to the WP admin screen?
>
> A question - does this plugin puts any references to other code? I mean if I remove it via FTP, do I have to make any other changes in my WP?

No, renaming the plugin folder would've completely removed the plugin from the system.

This issue sounds like an issue of using an Object Cache and/or cookie problem.. @mikolajek Did you find anything to resolve this? I'm tempted to close this issue unless some more information can be provided.

**Closed** 2024-12-02 22:48 UTC
