### ISSUE TITLE
U2F device ineligible.  When registering ONLYKEY

### ISSUE THREAD

**Issue by bmatusiak** [WordPress/two-factor#343] opened 2020-04-22 12:12 UTC
I use this key,  http://onlykey.io/sea

i have 2x of them..    (it supports a BACKUP and RESTORE feature....  so it can look like the same u2f certificate)

I can only register 1 of them.

it says "U2F device ineligible."
Its not its using "serial" information if found duplicate key is found during registration.
It should ASK for serial information of the key if a possible duplicate key is registered.

**Comment by kasparsd** [comment] 2020-04-30 06:20
Thanks for reporting the issue @bmatusiak. Could you please elaborate on the problem and the suggested solution here?

Most of the U2F logic is coming from the browser so we can't really get around these limitations.

**Comment by bmatusiak** [comment] 2020-05-01 05:38
OK with onlykey, I can dupe a key.  by doing back up and a restore to another key. somehow during login.. it fails..  I would have to do some testing to pin point a solution

**Comment by kasparsd** [comment] 2020-05-01 05:50
Thanks for the confirmation @bmatusiak! Since it appears to be related to a specific device and we can't really reproduce this and fix it in code I'm going to close this for now. Feel free to comment and reopen if you get more detail on what the fix could be.

**Closed by kasparsd** 2020-05-01 05:50 UTC
Labels: FIDO U2F, Question
