### ISSUE TITLE
wp-admin redirects to 404 or yubikey pop-up does not appear on login

### ISSUE THREAD

**Issue by markdahmke** [WordPress/two-factor#563] opened 2023-05-03 15:41 UTC
### Describe the bug

Just started to occur on several of the WP sites I manage. Disabling the two factor plugin resolves 404 error and allows login.
I haven't had time to try disabling all other plugins.

### Steps to Reproduce

on login, either 
1) /wp-admin redirects to 404 
OR 
2) yubikey prompt pop-up does not appear after entering username/password.

### Environment information

Running PHP 7.4.33, two-factor 0.81, wordpress 6.2. Wordfence.

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that you have tested with all plugins deactivated except Two-Factor.

No

**Comment by dd32** [comment] 2023-05-25 07:09
Without any further followup, I'm closing this, assuming that it's a duplicate of #423 and/or possibly a security plugin interfering.

Please re-open if the above comment doesn't explain the situation correctly.

**Closed by dd32** 2023-05-25 07:09 UTC
Labels: Bug
