### ISSUE TITLE
Force all users to configure/use two-factor

### ISSUE THREAD

**Issue by neilstuartcraig** [WordPress/two-factor#394] opened 2021-01-01 15:46 UTC
Hi all
I recently found this plugin via Twitter and it looks perfect for our sites (2 schools in the UK). I have been searching docs and issues and am confused as to the status of enforcing 2FA for all users - is this currently supported?
If so (even if via adding/editing code), please could you point me in the right direction? 
Apologies if this is documented, I have been searching/trying for about an hour now and had no joy.
Cheers!

**Comment by jaredatch** [comment] 2021-01-01 17:39
There is a long-standing PR for this, but that status is unknown and there is no timeline that I can tell.

WordPress VIP accomplishes this through various hooks, so if you don't need a UI you can go off of what they have done :)

https://github.com/WordPress/two-factor/pull/239#issuecomment-579177588

**Comment by kasparsd** [comment] 2021-05-18 19:06
Closing as a duplicate of #255 and #249.

@neilstuartcraig Here is the code for enforcing and enabling the two-factor authentication for all users:

https://github.com/WordPress/two-factor/issues/307#issuecomment-624843209

**Closed by kasparsd** 2021-05-18 19:06 UTC
