### ISSUE TITLE
Add force users to enable two-factor on next login

### ISSUE THREAD

**Issue by loftwah** [WordPress/two-factor#451] opened 2022-08-31 03:17 UTC
I'd like the ability to be able to force users to enable two-factor authentication on next login. This is a common feature in certain web applications and it would be handy to be able to set an option that forces all of the users to turn it on at next available opportunity. Even better if this can be done in cases where the server does not have SMTP capability.

**Comment by alexclst** [comment] 2022-09-19 21:35
I'd love this not just for individual users, but for anyone in given roles or higher (ie, set it at Author, and Authors, Editors, and Admins are all forced). I also think that it would be ideal if this stays in force, and therefore locks someone out if they ever turn off 2FA when their account falls into such a group. It would be nice to also force a type of 2FA on these users, so that I can disallow email 2FA for admins, for example.

It also seems that this is somewhat related to #239.

**Comment by loftwah** [comment] 2022-09-20 04:52
You're right, it is similar. I promise I tried to search for similar issues :)

**Comment by iandunn** [comment] 2022-10-19 16:09
I'm gonna close this because it looks like a duplicate of #255 / #239, but let me know if there's anything distinct that I missed.

**Closed by iandunn** 2022-10-19 16:09 UTC

**Comment by loftwah** [comment] 2022-10-21 00:50
It all looks the same to me. Thank you, I'm looking forward to seeing this in the plugin sometime.
