### ISSUE TITLE
Last Login

### ISSUE THREAD

**Issue by capstonedesign** [WordPress/two-factor#581] opened 2023-07-11 12:14 UTC
### Describe the bug

Hello. I am not sure if this is a bug. However, for our site whenever the Two Factor plugin is on, the user's last login meta information is not updated. When I disable the plugin, the last login meta information accurately captures when the user logged in. Any suggestions, or is this a bug?

### Steps to Reproduce

1. Enable Two Factor
2. Log in
3. In the database go to the users "last_login" meta column and you'll see it's not updated.

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that you have tested with all plugins deactivated except Two-Factor.

No

**Comment by kasparsd** [comment] 2024-09-19 08:35
Marking this as duplicate of #592.

**Closed** 2024-09-19 08:36 UTC
Labels: Bug
